LengerLonger/config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
 resources :users do 
  resources :profile
 end

end

LengerLonger/app/models/cartoon.rb
class Cartoon
require 'net/http'

  def self.joke
    uri= URI.parse('http://xkcd.com/info.0.json')
    @response = JSON.parse(Net::HTTP.get(uri))
  end

end

LengerLonger/app/models/fact.rb
class Fact
  require 'net/http'

  def get_fact
    uri= URI.parse("http://numbersapi.com/" + formatted_request)
    @response = Net::HTTP.get(uri)
  end

  def formatted_request
    num = rand(0...2000)
    type = %w(trivia math date year)
    type[rand(0..3)]
    @response = "#{num}/#{type[rand(0..3)]}"
  end
end

LengerLonger/app/models/joke.rb
class Joke
require 'net/http'

  def self.joke
    uri= URI.parse('http://xkcd.com/info.0.json')
    @response = JSON.parse(Net::HTTP.get(uri))
  end
  
end

LengerLonger/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

LengerLonger/app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_secure_password 
end

LengerLonger/app/models/weather.rb
class Weather
  require 'typhoeus'

  def self.get_daily_weather
     response = Typhoeus::Request.get("https://api.forecast.io/forecast/#{ENV['API_KEY']}/41.8781136,-87.6297982")
    JSON.parse(response.body) if response.code == 200
  end

end

LengerLonger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_login_path_for(resource)
    profile_path(resource)
  end

  def after_user_new_path_for(resource)
    profile_path(resource)
  end


  def current_user
    @current_user ||=User.find_by(id:session[:user_id]) if session[:user_id]
  end

  def logged_in?
    session[:user_id].present?
  end

  def authorize
    redirect_to '/login' unless current_user
  end

  def user_profile
    @profile =  Profile.find_by(user_id: current_user.id)
  end

  helper_method :authorize
  helper_method :user_profile

end

LengerLonger/app/controllers/pages_controller.rb
require 'net/http'

class PagesController < ApplicationController
  
  def index
    @weather = Weather.get_daily_weather
    @fact = Fact.new.get_fact
  end


end

LengerLonger/app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :find_user

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    @profile.save
    redirect_to root_path 
  end

  def show
    
  end

  def edit
    @profile = Profile.find_by(user_id: params[:user_id])
  end

  private
  def find_user
    @user =  User.find(session[:user_id])
  end
  def profile_params
    params.require(:profile).permit(:city, :fav_quote, :goal)
  end

end

LengerLonger/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create  
    current_user = User.find_by(email: params[:user][:email])
    if current_user && current_user.authenticate(params[:user][:password])
      session[:user_id] = current_user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end  
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

LengerLonger/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def show
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:notice] = "Something when wrong, please try again"
      render :new
    end 
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

LengerLonger/app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    session[:user_id] != nil
  end

  def user_profile
    @profile =  Profile.find_by(user_id: current_user.id)
  end
end

LengerLonger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LengerLonger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
  <script src="http://quotesondesign.com/api/3.0/api-3.0.js" type="text/javascript" charset="utf-8"></script>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</head>
<body>
  <header>
    <h2>Daily Starter</h2>
      <% if current_user %>
      <h1>Hi <%= current_user.first_name %>! </h1>
      <% end %>
  </header>
  <nav>
    <li><%= link_to "Home", root_path %></li>
    <% if logged_in? %>
      <% if current_user.profile.present?%>
        <li><%= link_to "Profile", user_profile_path(user_profile.id, current_user.id) %></li>
      <% else %>
       <li><%= link_to "Create Profile",  new_user_profile_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Logout", logout_path %></li>
    <% else %>
      <li><%= link_to "Register", new_user_path %></li>
      <li><%= link_to "Login", login_path %></li>  
    <% end %>
  </nav>

<%= yield %>

<footer>
  <p>Built by <%= link_to "CorainChicago", "http://corainchicago.github.io/" %></p>
</footer>

</body>
</html>

LengerLonger/app/views/pages/index.html.erb
<div class="fact_circle">
  <p><%= @fact %></p>
</div>


<div class="center-box">
  <% @response = Cartoon.joke %>
  <p><%= @response["title"] %></p>
  <img src="<%= @response["img"]%>">
</div>


<div class="quotes">
  <blockquote id="qod-quote"></blockquote>
</div>

<div class="weather"> 
  <p>Today's weather is:  <%= @weather["currently"]["summary"] %></p>
  <p>Current Temperature: <%= @weather["currently"]["temperature"].to_i  %></p>
  <p>Precipiation Chance: <%= @weather["daily"]["precipProbability"].to_i %>%   Humidity: <%= @weather["daily"]["Humidity"].to_i %>%</p>
  <p>Summary: <%= @weather["daily"]["summary"] %></p>
</div>

<div class="user_profile_info">
  <% if current_user && user_profile %>
    <p><%= user_profile.fav_quote %></p>
    <p><%= user_profile.goal %></p>
  <% else %> 
    <p>"Whatever you are, be a good one." -Abraham Lincoln</p>
    <p>Goal: Make this day yours!</p>
  <% end %> 
</div>

</div>

LengerLonger/app/views/users/new.html.erb
<div class"new_user">
  <%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_area :first_name %>
    <%= f.label :last_name %>
    <%= f.text_area :last_name %>
    <%= f.label :email %>
    <%= f.text_area :email %>
    <%= f.label :password %>
    <%= f.text_area :password %>
    <%= f.submit "Register" %>
  <% end %>
</div>

LengerLonger/app/views/users/show.html.erb
<h2>Hi Puppy</h2>

<h2><%= @profile.city %></h2>